Update validators to support validation of tasks
rapid7/icon-integrations-validators pull request #107
Opened 2020-09-28 14:12 UTC by gusingh-r7

## Description
- Update validators to support validation of tasks

## Testing

2020-09-29 17:28 UTC, gusingh-r7 commented
FYI, Unit tests are failing as changes are dependent on rapid7/icon-integrations-plugin-spec#10. We need to release `icon-integrations-plugin-spec` to fix unit tests failures.

2020-10-06 15:40 UTC, jmcadams-r7 requested changes

2020-10-06 15:40 UTC, jmcadams-r7 commented on icon_validator/rules/plugin_validators/description_validator.py
> +                    raise ValidationException(f"{dict_key} key '{key}' error.", e)
Keep the original description here. Generically saying error will drive me nuts trying to figure out what went wrong.

2020-10-06 16:02 UTC, mhofert-r7 approved these changes

2020-10-06 17:12 UTC, jmcadams-r7 approved these changes

2020-10-06 18:19 UTC, merged