Add Version Pin Validator
rapid7/icon-integrations-validators pull request #108
Opened 2020-11-08 22:09 UTC by r7-kszczepanskagorna

## Description
Add Version Pin Validator

## Testing
There was added unit test.

2020-11-09 17:04 UTC, mrinehart-r7 requested changes

2020-11-09 17:04 UTC, mrinehart-r7 commented on icon_validator/rules/plugin_validators/version_pin_validator.py
> +            if not re.match(r'[^=]*?==[^=]*?', requirements_text_one_element):
We'll need to make sure the regex here validates correctly against the valid version specifiers defined in PEP 508: https://www.python.org/dev/peps/pep-0508/#complete-grammar Under the `version_cmp` property

2020-11-11 13:28 UTC, jmcadams-r7 approved these changes

2020-11-11 19:55 UTC, mrinehart-r7 approved these changes

2020-11-11 19:55 UTC, merged