Add CloudReadyValidator
rapid7/icon-integrations-validators pull request #127
Opened 2021-04-18 21:10 UTC by r7-kszczepanskagorna

## Description
Add CloudReadyValidator

## Testing
There are unit tests

2021-04-19 11:58 UTC, jschipp-r7 commented
@r7-kszczepanskagorna Python linting check is failing

2021-04-19 12:05 UTC, jschipp-r7 requested changes

2021-04-19 12:05 UTC, jschipp-r7 commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                "For Cloud Ready plugins python runtime must be in 4+ version. "
```suggestion
                "The python runtime must be in 4+ version to be Cloud Ready"
```

2021-04-19 12:05 UTC, jschipp-r7 commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                "In Cloud Ready plugin 'USER' must be set to 'nobody' in Dockerfile. "
```suggestion
                "Plugin 'USER' must be set to 'nobody' in Dockerfile to be Cloud Ready"
```

2021-04-19 12:05 UTC, jschipp-r7 commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                                "Cloud Ready plugin can't have any system level command line utilities. "
```suggestion
                                "A Cloud Ready plugin cannot have any calls to system-level command-line utilities. "
```

2021-04-19 12:06 UTC, jschipp-r7 commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                "In Cloud Ready plugin 'enable_cache' must set to 'false'. "
This enabled by default, so long as the `enable_cache` is not set to True it will be turned off

2021-04-19 15:53 UTC, r7-kszczepanskagorna commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                "In Cloud Ready plugin 'enable_cache' must set to 'false'. "
So as I understand, if 'enable_cache' is set to True or this key is missing, enable cache exist. If 'enable_cache' is set to False (is not True), this is behavior which we need in Cloud Ready. That is correct?

2021-04-19 21:52 UTC, r7-kszczepanskagorna commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                "In Cloud Ready plugin 'enable_cache' must set to 'false'. "
Ok, Thanks :) Validator supports this case and also we test it to be sure :)

2021-04-20 13:30 UTC, jschipp-r7 approved these changes

2021-04-20 13:31 UTC, jschipp-r7 commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                "The python runtime must be in 4+ version to be Cloud Ready"
```suggestion
                "The python runtime must be in 4+ version to be Cloud Ready."
```

2021-04-20 13:31 UTC, zyoutz-r7 approved these changes
Looks great! 👍🏻

2021-04-20 13:31 UTC, jschipp-r7 commented on icon_validator/rules/plugin_validators/cloud_ready_validator.py
> +                "'enable_cache' must set to 'false' for a plugin to be Cloud Ready"
```suggestion
                "'enable_cache' must set to 'false' for a plugin to be Cloud Ready."
```

2021-04-20 13:32 UTC, jschipp-r7 approved these changes

2021-04-20 13:34 UTC, zyoutz-r7 approved these changes

2021-04-20 13:35 UTC, merged