Add HelpExampleValidator and improve EncodingValidator
rapid7/icon-integrations-validators pull request #132
Opened 2021-06-22 18:28 UTC by r7-kszczepanskagorna

## Description
Add HelpExampleVadalitor to  identify invalid JSON examples
Improve EncodingValidator to print all bad characters in one time

Tickets: MC-56 and MC-381

## Testing
Unit test

2021-06-22 18:48 UTC, jschipp-r7 approved these changes

2021-06-22 18:48 UTC, jschipp-r7 commented
@r7-kszczepanskagorna looks like a few unit tests are failing

2021-06-29 19:35 UTC, jschipp-r7 submitted a review, later dismissed

2021-06-29 19:39 UTC, jmcadams-r7 requested changes

2021-06-29 19:39 UTC, jmcadams-r7 commented on icon_validator/rules/plugin_validators/encoding_validator.py
> +            EncodingValidator.validator_errors.append(f"A forbidden characters was found in the '{key}' field of the spec.yaml file: {set(wrong_characters)}")
```suggestion
            EncodingValidator.validator_errors.append(f"A forbidden character(s) was found in the '{key}' field of the spec.yaml file: {set(wrong_characters)}")
```

2021-06-29 19:39 UTC, jmcadams-r7 commented on README.md
> +* 2.39.0 - Add HelpExampleValidator | Improve EncodingValidator by print all forbidden characters in one time
```suggestion
* 2.39.0 - Add HelpExampleValidator | Improve EncodingValidator by printing all forbidden characters at one time
```

2021-06-29 19:50 UTC, jschipp-r7 approved these changes

2021-06-29 19:51 UTC, jmcadams-r7 approved these changes

2021-06-29 19:54 UTC, merged