[MC-659] Add ( in screnshot title
rapid7/icon-integrations-validators pull request #137
Opened 2021-08-15 20:21 UTC by r7-kszczepanskagorna

## Description
Ticket MC-659
Add in WorkflowScreenshotValidator check parenthesis in screenshot title

## Testing
Unit tests

2021-08-20 14:59 UTC, mrinehart-r7 requested changes

2021-08-20 14:59 UTC, mrinehart-r7 commented on README.md
> +* 2.40.1 - Add in WorkflowScreenshotValidator check parenthesis in screenshot title
```suggestion
* 2.40.1 - Add in WorkflowScreenshotValidator to check parenthesis in screenshot title
```

2021-08-20 14:59 UTC, mrinehart-r7 submitted a review, later dismissed

2021-08-23 14:55 UTC, mberezin-r7 approved these changes

2021-09-16 18:44 UTC, mrinehart-r7 approved these changes

2021-09-16 18:45 UTC, jrose-r7 approved these changes

2021-09-16 18:48 UTC, merged