SOAR-8575 Separated UseCaseValidator for workflow and plugins validation
rapid7/icon-integrations-validators pull request #150
Opened 2022-02-23 19:59 UTC by tcheng-r7

## Proposed Changes

### Description

Describe the proposed changes:

  - Currently the UseCaseValidator is used for both plugin and workflow validation. With the large update to workflow use case tags, workflows can no longer share the same use cases with plugins. The new WorkflowUseCaseValidator pulls in use cases from the Hub API and checks PRs against those use cases. 

## PR Requirements

Developers, verify you have completed the following items by checking them off:

- [ ] Unit tests written for any new or updated code
- [ ] Version bumped within setup.py
- [ ] Changelog entry added

2022-02-23 20:21 UTC, mberezin-r7 approved these changes

2022-02-23 22:59 UTC, mrinehart-r7 requested changes

2022-02-23 22:59 UTC, mrinehart-r7 commented on README.md
> +* 2.44.3 - Separated UseCaseValidator for workflows as plugins and workflows now have different usecase tags
```suggestion
* 2.45.0- Separated UseCaseValidator for workflows as plugins and workflows now have different usecase tags
```
Minor version bump as it's technically a new validator

2022-02-23 22:59 UTC, mrinehart-r7 commented on icon_validator/rules/workflow_validators/workflow_use_case_validator.py
> +            query = f"after={response_json['pageInfo']['endCursor']}"
```suggestion
        params = {
            "first": 1000
            "types": "usecase"
        }
        
        has_next = True
        while has_next:
            response = requests.get(url=f"https://extensions-api.rapid7.com/v2/public/tags", params=params)
            response_json = response.json()
            approved_usecases.extend(WorkflowUseCaseValidator.get_approved_usecase_tags(response_json))
            if not response_json["pageInfo"]["hasNextPage"]:
                has_next = False

            params["after"] = response_json['pageInfo']['endCursor']
```
Cleaned up the request a bit - you can pass dictionaries into the `params` arg in requests.get() to use query parameters in a cleaner way. Also switched the for loop to a while. I highly doubt we'd ever paginate 10000 times, but you never know 🤷🏻 . Also fixed the query update on line 29 - you were clearing out the existing params which was yielding an HTTP 400 when I tried it in the browser.

Give this code a shot

2022-02-23 22:59 UTC, mrinehart-r7 commented on icon_validator/rules/workflow_validators/workflow_use_case_validator.py
> +            if not use_cases or not len(use_cases):
```suggestion
            if not use_cases:
```
You can consolidate them as `if not var` checks for False, None, and 0 length

2022-02-23 22:59 UTC, mrinehart-r7 commented on icon_validator/rules/workflow_validators/workflow_use_case_validator.py
> +    def get_approved_usecase_tags_with_paging() -> [str]:
If you want a fun thing to try (not required for this PR, but could improve performance if this usecase list ever grew huge), you can turn this function into a [generator](https://wiki.python.org/moin/Generators) that yields usecases that can be compared against. You could then try comparing all the usecases in the workflow against the current set, and if they don't match, then get the next set from the generator (which would be the next page from the API), and continue until all possible usecase matches have been exhausted.

2022-02-23 22:59 UTC, mrinehart-r7 commented on setup.py
> +    version="2.44.3",
```suggestion
    version="2.45.0",
```

2022-02-24 15:17 UTC, mberezin-r7 approved these changes

2022-02-24 19:29 UTC, mrinehart-r7 approved these changes

2022-02-24 19:35 UTC, merged